-- WasteBank Supabase Schema (DDL)
-- Catatan:
-- - Koordinat disimpan sebagai TEXT dengan format: "lat,lon"
-- - Status menggunakan enum text + CHECK constraint
-- - UI saat ini masih memakai guestbook/reports; setelah integrasi, frontend akan diarahkan ke tabel baru.

-- WasteBank Supabase Schema
--
-- Goal:
-- 1) Permohonan (Edukasi & Sosialisasi) -> tabel baru: permohonan
-- 2) Buku Tamu (Ulasan) -> tetap gunakan tabel guestbook yang sudah ada
-- 3) Laporan tumpukan sampah liar (Aduan) -> gunakan tabel reports yang sudah ada, namun tambah: image & koordinat
-- 4) Admin BSU: pastikan koordinat tersimpan dan terlihat (kolom sudah ada di admin code: bank_sampah.coordinates)
-- 5) Jenis sampah untuk BSU -> implementasi via kolom volume per jenis (plastic/paper/iron/bottle/glass/oil) pada bank_sampah
--
-- Catatan koordinat:
-- - Format TEXT: "lat,lon" (sesuai permintaan)



-- =====================================
-- 1) PERMOHONAN (Edukasi & Sosialisasi) - tabel baru
-- ====================================
create table if not exists public.permohonan (
  id bigint generated by default as identity primary key,

  nama_instansi text not null,
  tanggal_pelaksanaan text not null,

  tema text,

  nama_narahubung text not null,
  whatsapp_narahubung text,
  estimasi_peserta integer,

  deskripsi text,

  status text not null default 'Baru',
  created_at timestamptz not null default now(),

  constraint permohonan_status_check check (status in ('Baru','Diproses','Selesai','Ditolak'))
);

create index if not exists permohonan_created_at_idx on public.permohonan (created_at desc);

-- =====================================
-- 2) MIGRASI/ALTER reports untuk dukung image + koordinat
-- =====================================
-- Pastikan tabel `reports` sudah ada.

alter table public.reports
  add column if not exists image text;

alter table public.reports
  add column if not exists koordinat text;

-- Index untuk pencarian admin
create index if not exists reports_koordinat_idx on public.reports (koordinat);
create index if not exists reports_created_at_idx on public.reports (created_at desc);

-- =====================================
-- 3) (Opsional) Hapus tabel duplikat yang sebelumnya dibuat
-- =====================================
-- Jika Anda sebelumnya sudah menjalankan versi lama dan tabel duplikat muncul,
-- maka gunakan blok ini.
--
-- Aktifkan dengan menghapus komentar tanda -- pada bagian drop berikut.

drop table if exists public.ulasan;
drop table if exists public.bank_sampah_jenis;
drop table if exists public.aduan;

-- =====================================
-- OPTIONAL: RLS
-- =====================================
-- Catatan: Project Anda mungkin sudah punya RLS policy/aturan lain.
-- Jika ingin menyalakan RLS, gunakan sesuai kebutuhan.



